version: "3.5"
networks:
  scheme-network:
    name: scheme-network
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  my-running-load-balancer:
    hostname: my-running-load-balancer
    container_name: my-running-load-balancer
    image: my-load-balancer
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - sys_ptrace
    ports:
      - "2222:22"
    networks:
      scheme-network:
        ipv4_address: 172.18.1.2
    mac_address: 02:42:ac:12:01:02

  my-running-nat:
    hostname: my-running-nat
    container_name: my-running-nat
    image: my-load-balancer
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - sys_ptrace
    ports:
      - "2223:22"
    networks:
      scheme-network:
        ipv4_address: 172.18.1.3
    command: >-
      sh -c "apt-get install -y conntrack &&
      tail -f /dev/null"

  my-running-client:
    hostname: my-running-client
    container_name: my-running-client
    image: my-proxygen
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - sys_ptrace
    networks:
      scheme-network:
        ipv4_address: 172.18.0.2
    command: >-
      sh -c "apt-get install -y iproute2 iptables conntrack tcpdump &&
      tail -f /dev/null"

  my-proxygen-server-0:
    hostname: my-proxygen-server
    container_name: my-proxygen-server-0
    image: my-proxygen
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - sys_ptrace
    ports:
      - "2224:22"
      - "5000:5000"
    networks:
      scheme-network:
        ipv4_address: 172.18.2.2
    mac_address: 02:42:ac:12:02:02
    volumes:
      - ./quic-lb-proxygen:/usr/src/proxygen
    links:
      - my-running-nat
    command: >-
      sh -c "apt-get install -y iproute2 iptables tcpdump conntrack python3-pip &&
      ip route del 172.18.0.0/16 &&
      ip r a 172.18.0.0/16 via 172.18.1.3 dev eth0 onlink &&
      ip route del default &&
      ip r a default via 172.18.1.3 dev eth0 onlink &&
      echo finished everything &&
      ./proxygen/proxygen/_build/proxygen/httpserver/hq --mode=server --host=172.18.2.2 --port=6666 --early_data=true"


#      pip3 install --upgrade setuptools &&
#      pip3 install gdbgui &&
#      pip3 install --upgrade gdbgui &&
#      apt-get install -y gdbserver &&
#      apt-get install -y gdb &&
#      tail -f /dev/null"
#      ./proxygen/proxygen/_build/proxygen/httpserver/hq --mode=server --qlogger_path=. --host=172.18.2.2 --port=6666 --early_data=true"

  my-proxygen-server-1:
    hostname: my-proxygen-server
    container_name: my-proxygen-server-1
    image: my-proxygen
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - sys_ptrace
    networks:
      scheme-network:
        ipv4_address: 172.18.2.3
    mac_address: 02:42:ac:12:02:03
    volumes:
      - ./quic-lb-proxygen:/usr/src/proxygen
    links:
      - my-running-nat
    command: >-
      sh -c "apt-get install -y iproute2 iptables tcpdump conntrack &&
      ip route del 172.18.0.0/16 &&
      ip r a 172.18.0.0/16 via 172.18.1.3 dev eth0 onlink &&
      ip route del default &&
      ip r a default via 172.18.1.3 dev eth0 onlink &&
      ./proxygen/proxygen/_build/proxygen/httpserver/hq --mode=server --host=172.18.2.3 --port=6666 --early_data=true"
    
